services:
  mysql_auth:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: foodapp
      MYSQL_DATABASE: foodapp_auth
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: foodapp
    ports: ["3306:3306"]
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
      
  mysql_user:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: foodapp
      MYSQL_DATABASE: foodapp_user
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: foodapp
    ports: ["3307:3307"]
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

  redis:
    image: redis:7
    ports: ["6379:6379"]