version: '3.8'


services:
  mysql_auth:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: foodapp
      MYSQL_DATABASE: foodapp_auth
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: foodapp
    ports: ["3306:3306"]
    networks:
      - foodapp_network
    volumes:
      - mysql_auth_data:/var/lib/mysql

  mysql_user:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: foodapp
      MYSQL_DATABASE: foodapp_user
      MYSQL_USER: foodapp
      MYSQL_PASSWORD: foodapp
    ports: ["3307:3306"]
    networks:
      - foodapp_network
    volumes:
      - mysql_user_data:/var/lib/mysql

  redis:
    image: redis:7
    ports: ["6379:6379"]
    networks:
      - foodapp_network
    volumes:
      - redis_data:/data

networks:
  foodapp_network:
    driver: bridge
volumes:
  mysql_user_data:
  mysql_auth_data:
  redis_data:
