const AUTH_GRPC = "AUTH_GRPC";
const USER_GRPC = "USER_GRPC";
const PAYMENT_GRPC = "PAYMENT_GRPC";
const RESTAURANT_GRPC = "RESTAURANT_GRPC";
const ORDER_GRPC = "ORDER_GRPC";

const AUTH_SERVICE = "AuthService";
const USER_SERVICE = "UserService";
const PAYMENT_SERVICE = "PaymentService";
const RESTAURANT_SERVICE = "RestaurantService";
const ORDER_SERVICE = "OrderService";

export { AUTH_GRPC, USER_GRPC, PAYMENT_GRPC, RESTAURANT_GRPC, ORDER_GRPC, AUTH_SERVICE, USER_SERVICE, PAYMENT_SERVICE, RESTAURANT_SERVICE, ORDER_SERVICE };
