version: "3.8"
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: foodapp
      POSTGRES_PASSWORD: foodapp
      POSTGRES_DB: foodapp
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  nats:
    image: nats:2
    ports: ["4222:4222","8222:8222"]
